yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit, name='post_edit'
    ),
    path(
        "<str:username>/<int:post_id>/comment",
        views.add_comment, name="add_comment"
    ),
    path(
        '<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls import handler404, handler500
from django.views.static import serve


handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [re_path(
        r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT, }),
    ]
    urlpatterns += [re_path(
        r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
    ]

yatube/templates/includes/author.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
        <div class="card-body">
            <div class="h2">
                {{ author.first_name }} {{ author.last_name }}
            </div>
            <div class="h3 text-muted">
                @{{ author.username }}
            </div>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Подписчиков: {{ author.following.count }} <br />
                    Подписан: {{ author.follower.count }}
                </div>
            </li>
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Количество записей: {% if page.paginator %}{{ page.paginator.count }}{% else %}{{ posts_count }}{% endif %}
                </div>
            </li>
            <li class="list-group-item">
                {% if user != author %}
                    {% if following %}
                    <a class="btn btn-lg btn-light" 
                            href="{% url 'posts:profile_unfollow' author.username %}" role="button"> 
                            Отписаться 
                    </a> 
                    {% else %}
                    <a class="btn btn-lg btn-primary" 
                            href="{% url 'posts:profile_follow' author.username %}" role="button">
                    Подписаться 
                    </a>
                    {% endif %}
                {% endif %}
            </li> 
        </ul>
    </div>
</div>

yatube/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form action="{% url 'posts:add_comment' post.author.username post.id %}" method="post">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                @{{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

yatube/templates/includes/follow_button.html
<li class="list-group-item">
    {% if following %}
    <a class="btn btn-lg btn-light" 
            href="{% url 'posts:profile_unfollow' profile.username %}" role="button"> 
            Отписаться 
    </a> 
    {% else %}
    <a class="btn btn-lg btn-primary" 
            href="{% url 'posts:profile_follow' profile.username %}" role="button">
    Подписаться 
    </a>
    {% endif %}
</li> 

yatube/templates/includes/footer.html
<footer class="py-5 bg-dark">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <div class="container"><p class="m-0 text-center text-white">Социальная сеть <span style="color:red">Hobby</span>World © {% now 'Y' %}, все права защищены.</p></div>
</footer>

yatube/templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if not follow %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %} 

yatube/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Hobby</span>World</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active"> 
                    <a class="nav-link" href="{% url 'posts:profile' user.username %}">
                        Пользователь: {{ user.username }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:new_post' %}">Новая запись</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'password_change' %}">Изменить пароль</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Выйти</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Войти</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

yatube/templates/includes/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_item.html
<div class="card mb-4">
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img-top" src="{{ im.url }}" alt="Card image cap" />
  {% endthumbnail %}
  <div class="card-body">
    <h2 class="card-title">{{ post }}...</h2>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    {% if post.group %}
    <a class="card-link muted" href="{% url 'posts:group' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}
    {% if post.comments.exists %}
    <div>
      Комментариев: {{ post.comments.count }}
    </div>
    {% endif %}
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>
        {% if user == post.author %}
        <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}
      </div>
    </div>
    <div class="card-footer text-muted">
      Опубликовано {{ post.pub_date }}
      <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
        <strong> @{{ post.author }}</strong>
      </a>
    </div>
  </div>
</div>